version: "2.3"
services:
  web:
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    container_name: CentralBankTask
    ports:
      - "5000:5000"
    volumes:
      - ./config/database.yml:/app/database.yml
      - ./config/main.yml:/app/main.yml
      - ./config/urls.yml:/app/urls.yml
      - ./build/PostgreSQL/DeleteTables.sql:/app/DeleteTables.sql
      - ./build/PostgreSQL/Fill.sql:/app/Fill.sql
      - ./build/PostgreSQL/CreateTables.sql:/app/CreateTables.sql
      - ./files/template/index.html:/app/index.html


  postgres:
    container_name: BankInfo
    image: postgres:latest
    environment:
      - POSTGRES_USER=constantil
      - POSTGRES_PASSWORD=293456QwErty
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U constantil" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./build/PostgreSQL/CreateTables.sql:/docker-entrypoint-initdb.d/init.sql
      - ./build/PostgreSQL/DeleteTables.sql:/app/DeleteTables.sql
      - ./build/PostgreSQL/Fill.sql:/app/Fill.sql
